### ISSUE TITLE
Error when running app

### ISSUE THREAD

**Issue by johnlim** [auth0-samples/auth0-spring-security-mvc-sample#1]
Hi, I get the following error message when I run mvn spring-boot:run
```Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project auth0-spring-security-mvc-sample: Fatal error compiling: invalid target release: 1.8 -> [Help 1]```

Maven version is 3.3.9. Could you please advise accordingly? Thanks.

**Comment by arcseldon** [comment]
@johnlim - what version of Java are you using? The sample was written and tested against Java 1.8. That said, the Java 1.7 should also work - however, you may need to adjust the pom.xml Java properties version from 1.8 to 1.7.

Also google for information on your error, for example [here](http://stackoverflow.com/questions/28291691/fatal-error-compiling-invalid-target-release-1-8-help-1) as this may offer insights specific to your setup.

Please let me know how you get on.

**Comment by johnlim** [comment]
@arcseldon Thanks. Fixing the pom solved the issue.
