### ISSUE TITLE
outdated auth0 lock

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-spring-security-mvc-sample#11]
Samples using lock v10.0 when up-to-date version is 10.10. (AUTH-3751)

**Comment by HeikerAraujo** [comment]
This issue is affecting the Regular Web App JAVA spring Security sample projects. (login.jsp).

![lockversionoutdatedsampleproject](https://cloud.githubusercontent.com/assets/26749061/24734444/6b683bde-1a4b-11e7-8301-e20011187064.jpg)

**Comment by jimmyjames** [comment]
Hi @Amialc, as Auth0's product offering and this sample (along with supporting SDKs) have been updated since reporting, I'm going to close this issue. If you are still encountering issues, don't hesitate to reopen or create a new issue (just be sure to include updated debugging info). Thanks!
