### ISSUE TITLE
The README.md files contained in the project do not contain any instructions.

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-spring-security-mvc-sample#18]
The README.md files contained in the project do not contain any instructions.

![image](https://user-images.githubusercontent.com/26749061/29192083-fa385c9e-7ded-11e7-90c4-95c05a6ba55d.png)

**Comment by mathiasconradt** [comment]
This seems to be resolved, at least I cannot find an empty README.md anymore in the project.

**Comment by jimmyjames** [comment]
As @mathiasconradt the `README` is no longer empty, so closing this issue. If you have any other difficulties, don't hesitate to create a new issue!
