### ISSUE TITLE
Java Spring Security Webapp: Unformatted message

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/auth0-spring-security-mvc-sample#21]
After login, the message shown to welcome the user is not formatted properly and it is not clear if this is an error or is intended.

![capture-for-jira-screenshot-20171204-130533-880](https://user-images.githubusercontent.com/15818783/33609995-833a5674-d9a0-11e7-9602-28c91d0124ec.png)

**Comment by lbalmaceda** [comment]
That's just the "toString" implementation of the `Principal` class. The value [is passed to the jsp](https://github.com/auth0-samples/auth0-spring-security-mvc-sample/blob/master/01-Login/src/main/java/com/auth0/example/mvc/HomeController.java#L25) and then [used](https://github.com/auth0-samples/auth0-spring-security-mvc-sample/blob/master/01-Login/src/main/webapp/WEB-INF/jsp/home.jsp#L61) to display it. I understand that the text is not the best and could be improved, but it was there just to prove it was present.

**Comment by jimmyjames** [comment]
Hi @paulioceano - as @lbalmaceda mentioned this sample simply currently displays the raw value of the `Principal`, to illustrate successful login. We may provide better UI in the future, but for now the authenticated user's credentials are displayed as-is. If you have any other concerns or issues, don't hesitate to create a new issue. Thanks!
