### ISSUE TITLE
Allowed Logout URL: http://localhost:3000/login missing in quickstart instructions

### ISSUE THREAD

**Issue by mathiasconradt** [auth0-samples/auth0-spring-security-mvc-sample#29]
Quickstart instructions are missing the 'Allowed Logout URL: http://localhost:3000/login' in the instructions (when downloading the zip within the dashboard > Application(s) > Quick Start), though it's needed.
(Also seems to be the case in the other Java (regular webapps) quick starts.)

**Comment by jimmyjames** [comment]
We've updated the Quickstart to include adding the Allowed Logout URL (note it recently changed to `http://localhost:3000/`):

<img width="892" alt="updated-qs-logout" src="https://user-images.githubusercontent.com/276225/59383534-ae5abf80-8d25-11e9-8296-a4b9c4ffabc4.png">
