### ISSUE TITLE
Quickstart not working with JDK 11 (Oracle)

### ISSUE THREAD

**Issue by mathiasconradt** [auth0-samples/auth0-spring-security-mvc-sample#30]
Quickstart not working with JDK 11 (Oracle).

**Comment by jimmyjames** [comment]
Hi @mathiasconradt! This sample currently uses Spring Boot 1.5.6, which includes Spring 4. To properly support support JDK versions past 8, we'll need to update it to use later versions of Spring that will also support later versions of JDK.

**Comment by jimmyjames** [comment]
This Quickstart can now run with JDK 11 (#34). Please reopen if you continue to experience issues, thanks!
