### ISSUE TITLE
Missing features in demo to be really illustrative: Show ID token payload, verify token, scopes

### ISSUE THREAD

**Issue by mathiasconradt** [auth0-samples/auth0-spring-security-mvc-sample#32]
There are a few things missing in this quick start (but actually in all Java quick starts), so that it's not as illustrative as for example the SPA quick starts (Vue.js, etc.):

- No example how payload from ID token is retrieved.
- No example how to verify a token.
- No example how to pass scopes to the authorization request.

Something like this should be added to the `CallbackController` / `handle` method I suppose (not sure if it's best practice and all methods used optimal):

```
    String authorizeUrl = controller.buildAuthorizeUrl(req, redirectUri)
        //.withAudience(String.format("https://%s/userinfo", appConfig.getDomain()))  // I don't think is actually needed here
        .withScope("openid profile email email_verified")  // but this should be used to show "real" user profile info like email, username, etc.
        .build();
```

and

```
    DecodedJWT jwt = JWT.decode(tokens.getIdToken());
    // do something with jwt.getPayload();
    // ....

    try {
        JwkProvider provider = new UrlJwkProvider("https://<tenant>.eu.auth0.com/.well-known/jwks.json");
        Jwk jwk = provider.get(jwt.getKeyId());
        Algorithm algorithm = Algorithm.RSA256((RSAPublicKey) jwk.getPublicKey(),null);
        algorithm.verify(jwt);

        // or ...? 

        Verification verifier = JWT.require(algorithm);
        verifier.build().verify(jwt);

    } catch (JWTVerificationException exception){
        exception.printStackTrace();
        //Invalid signature/claims
    } catch (JwkException e) {
        e.printStackTrace();
    }
```

**Comment by jimmyjames** [comment]
Hi @mathiasconradt, this is really great feedback, thanks!

We recently made a change that addresses some of the issues you raised. Namely, demonstrating how to request profile-related scopes in the authorization request, and getting (and displaying) profile data from the ID token. You can find the changes in https://github.com/auth0-samples/auth0-spring-security-mvc-sample/pull/35. 

It still uses the `/userinfo` audience for token validation, but we can look to update further to demonstrate how to use the jwks to do token verification. I'm going to keep this issue open for continued tracking of this. The updated Quickstart to accompany the changes can be found [here](https://auth0.com/docs/quickstart/webapp/java-spring-security-mvc)

Thanks!
