### ISSUE TITLE
Authentication does not contain roles

### ISSUE THREAD

**Issue by RaffaeleSgarro** [auth0-samples/auth0-spring-security-mvc-sample#43]
The `Authentication` object initialized from the idToken doesn't contain any granted authority by default because it looks for `https://access.control/roles` claims which is non-standard, I guess (at least, my vanilla Auth0 doesn't show roles in this claim).

Start the provided sample app and set a breakpoint at: https://github.com/auth0-samples/auth0-spring-security-mvc-sample/blob/master/01-Login/src/main/java/com/auth0/example/mvc/CallbackController.java#L49

Roles can be retrieved via another call to the management API that unfortunately adds latency:

```java
AuthAPI authAPI = new AuthAPI(domain, clientId, clientSecret);
AuthRequest authRequest = authAPI.requestToken("https://" + domain + "/api/v2/");
TokenHolder holder = authRequest.execute();
ManagementAPI mgmt = new ManagementAPI(domain, holder.getAccessToken());
List<Role> roles = mgmt.roles()
		.list(new RolesFilter())
		.execute()
		.getItems();
 ```

but this in turn requires that the default Auth0 Management API is authorized and granted all relevant grants (for example via Dashboard > Machine to machine Applications).

Another option is adding the roles to the claim via a custom rule, but that should be documented somewhere because developing rules for Auth0 is very cumbersome and definitely not a beginner task (while on the other hand getting roles is a fundamental necessity for Auth0 users).

**Comment by RaffaeleSgarro** [comment]
Maybe it's enought to tell in the README and in the documentation about the following custom rule:

```
function (user, context, callback) {
  // https://auth0.com/docs/authorization/concepts/sample-use-cases-rules#add-user-roles-to-tokens
  const namespace = 'https://access.control';
  const assignedRoles = (context.authorization || {}).roles;

  let idTokenClaims = context.idToken || {};
  let accessTokenClaims = context.accessToken || {};

  idTokenClaims[`${namespace}/roles`] = assignedRoles;
  accessTokenClaims[`${namespace}/roles`] = assignedRoles;

  context.idToken = idTokenClaims;
  context.accessToken = accessTokenClaims;

  callback(null, user, context);
}
```

**Comment by jimmyjames** [comment]
Hi @RaffaeleSgarro - thanks for reporting this 🙏!

In talking to some other engineers, it appears this code is some leftover legacy code from an earlier Quickstart article. Since the [Quickstart](https://auth0.com/docs/quickstart/webapp/java-spring-security-mvc) is now focused just on login, this code is unnecessary and can cause confusion. I'll make a PR to remove it to avoid the confusion. Thanks!
