### ISSUE TITLE
Error after login

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-spring-security-mvc-sample#5]
After i've logged in using [01-Login](https://github.com/auth0-samples/auth0-spring-security-mvc-sample/tree/master/01-Login) sample, i've got this:
![image](https://cloud.githubusercontent.com/assets/1114365/18086574/4aef540c-6eb9-11e6-87d3-6d45d8863d8f.png)

**Comment by mpaktiti** [comment]
Hello @Amialc . I'm trying to reproduce this issue but I can't seem to, it works for me.

Can you please copy here the contents of your `auth0.properties`? I'm particularly interested in `domain` and `issuer`. Do you have the slash at the end?

For example:

```
auth0.domain: mydomain.eu.auth0.com
auth0.issuer: https://mydomain.eu.auth0.com/
```

**Comment by Amialc** [comment]
Hello @mpaktiti, thanks for advice, you were right, i've downloaded sample and `issuer` was not set. But now i've got another problem. When i'm trying to login, it redirects me to `/login` page back with message `Error! Please log in`, but in logs it's all good:
![image](https://cloud.githubusercontent.com/assets/1114365/18099354/cab42250-6eee-11e6-8a28-10d0e3c64620.png)
```
auth0.domain: tutorials.auth0.com
auth0.issuer: https://tutorials.auth0.com/
auth0.clientId:
auth0.clientSecret:
auth0.onLogoutRedirectTo: /login
auth0.securedRoute: /portal/*
auth0.loginCallback: /callback
auth0.loginRedirectOnSuccess: /portal/home
auth0.loginRedirectOnFail: /login
auth0.base64EncodedSecret: true
auth0.authorityStrategy: ROLES
auth0.servletFilterEnabled: false
auth0.defaultAuth0WebSecurityEnabled: false
auth0.connection: {CONNECTION}
auth0.customLogin: false
#auth0.customLogin: true
auth0.signingAlgorithm: HS256
#auth0.signingAlgorithm: RS256
#auth0.publicKeyPath: /WEB-INF/certificate/cert.pem
```

**Comment by arcseldon** [comment]
hi vlad,

This may be because in order to access the home page you must have role [ROLE_ADMIN](https://github.com/auth0-samples/auth0-spring-security-mvc-sample/blob/master/01-Login/src/main/java/com/auth0/example/AppConfig.java#L23)

Try adding a rule to your dashboard that automatically adds ROLE_ADMIN to your user profile and you should be successful in reaching the home page.

Here is such a [Rule](https://gist.github.com/arcseldon/05967294f6b25a924b4e7517b52f5e5a) just to get things working.

**Comment by arcseldon** [comment]
@Amialc ^^^^

**Comment by Amialc** [comment]
@mpaktiti @arcseldon thanks guys, now it's working, but i'm think no need so complex authentication (based on roles) on such start samples. 
Anyway, thanks.

**Comment by arcseldon** [comment]
@Amialc - i think you are right. 

@maria - for the 01-Login - we could remove the line `.antMatchers("/portal/**").hasAuthority("ROLE_ADMIN")` from the configuration and then it will do login without the need for any Rules to be set. That does make a lot of sense. What do you think?

**Comment by mpaktiti** [comment]
@arcseldon Sounds good. I can do the change.
