### ISSUE TITLE
09-MFA is empty

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-spring-security-mvc-sample#7]
If [09-MFA](https://github.com/auth0-samples/auth0-spring-security-mvc-sample/tree/master/09-MFA) don't need code changes, then probably better if there will be unchanged code.

**Comment by mpaktiti** [comment]
Hello @Amialc . This is the approach we chose to follow for MFA, have only a README file, and no code. If we added code in this then we would have to maintain it at one more place.

Thank you!
